name: Version check
on:
  schedule:
    - cron:  '15,45 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [stable, unstable]
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ matrix.branch }}
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Update version and commit changes
      run: |
        bash update.sh
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ matrix.branch }}
